### ISSUE TITLE
Error en la instalación.

### ISSUE THREAD

**Issue by lechuga16** [digiraldo/Minecraft-BE-Server-Panel-Admin-Web#1]
Me genero el siguiente error al ejecutar el script.
![Screenshot_6](https://user-images.githubusercontent.com/34782281/152906325-27247dfe-13bd-445e-bb5e-b0a85ee9c991.png)
El nombre del servidor no era "parceros", supongo que es un error de tipeo.

Sugiero añadir la instalación de git dentro del script.
Esta muy bueno su trabajo.

**Comment by digiraldo** [comment]
Hola [lechuga16](https://github.com/lechuga16)

Gracias por capturar el error y darlo a conocer, ya corregí el script para que este escriba el nombre del servidor en **server.properties**.

Me alegro que le halla gustado el trabajo, son meses de configuración y todavía estoy mejorándolo en mis ratos libres.
