### ISSUE TITLE
whitelist.json = allowlist.json

### ISSUE THREAD

**Issue by lechuga16** [digiraldo/Minecraft-BE-Server-Panel-Admin-Web#2]
Hola, en mi panel aparece los siguientes errores.

`Warning: file_get_contents(../../hlz/whitelist.json): failed to open stream: No such file or directory in /home/mcb/minecraftbe/panel/tablero/info.php on line 86`

`Warning: file_get_contents(/home/mcb/minecraftbe/panel/usuarios../../../hlz/whitelist.json): failed to open stream: No such file or directory in /home/mcb/minecraftbe/panel/usuarios/usuarios.php on line 2`

Por lo que estuve leyendo, el archivo whitelist.json fue renombrado a allowlist.json en una de sus versiones.
![Screenshot_7](https://user-images.githubusercontent.com/34782281/153113918-82d54c01-5620-4997-87ed-72b530f102d0.png)

La info la encontré en el siguiente hilo: https://github.com/itzg/docker-minecraft-bedrock-server/issues/148

**Comment by lechuga16** [comment]
otro detalle, es que en **server.properties** esta de la siguiente forma.

```
allow-list=true
# If true then all connected players must be listed in the separate allowlist.json file.
# Allowed values: "true" or "false"
```

**Comment by digiraldo** [comment]
Hola [lechuga16](https://github.com/lechuga16)

Gracias por la información suministrada. De acuerdo a las actualizaciones realizadas en el Servidor de Minecraft Bedrock Edition Server, realice los cambios de whitelist a allowlist de todo el código del repositorio, incluyendo white-list a allow-list de server.properties.

No cuento con un servidor a la mano para realizar las pruebas necesarias y verificar el buen funcionamiento, por tal motivo quedo atento si fue solucionado los errores al reinstalar su servidor de Minecraft BE, mientras monto de nuevo un Linux server para realizar personalmente la instalación del mismo.
