### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by lechuga16** [digiraldo/Minecraft-BE-Server-Panel-Admin-Web#3]
hola, este el botón de "Gestión de archivos" en la pagina de Shell me da 404.

`<a href="archivos.php" value="btnCerrar" class="btn btn-warning" type="submit" name="accion"><i class="fas fa-close"></i> Gestión Archivos</a>`

Además que el color del botón para llegar a la pagina de Shell es igual al fondo, por lo que es fácil que alguien nuevo no lo encuentre.
¿No seria mas útil dejarlo en la barra superior de navegación?.
![Screenshot_8](https://user-images.githubusercontent.com/34782281/153773111-4dece804-a428-4dda-b8a2-e8e233d204fa.png)

**Comment by digiraldo** [comment]
Hola [lechuga16](https://github.com/lechuga16)

Gracias por comentar, la razon de que este allí un poco oculto es porque esta en proceso de configuracion la administración o gestion de archivos, de igual manera está muy buena la sugerencia de dejarlo en la barra superior de navegación.

El botón Gestión de archivos, ya fue corregido.

Me parece genial que lo haya encontrado, solo el usuario propietario puede verlo, y es muy util para ir descargando los gamertag que estan en allowlist y los archivos de configuración e ir guardandolos como copias de seguridad.

Una consulta adicional, si el servidor lo configuró en una VPS, es posible agregar mi gamertag disaned a su servidor para ver como funciona, no soy un jugador muy activo y este proyecto solo lo tengo en un servidor local.

**Comment by lechuga16** [comment]
podría entregarle temporalmente un vps de testing por unos días para que pueda realizar sus modificaciones, necesitaría unos días para pedirlo.

**Comment by lechuga16** [comment]
ya tengo lista la cuenta para que pueda hace ensayos y pruebas. agrégueme por steam que es donde respondo mas rápido.
`https://steamcommunity.com/id/lechuga_/`
